# grafana/provisioning/datasources/influxdb-influxql.yaml
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    database: strain_bucket
    jsonData:
      httpMode: POST
      version: InfluxQL
      tags:
        environment: production
    secureJsonData:
      password: mytoken
